### ISSUE TITLE
ChildNodesLayout position of FIRST_CHILD_BY_PARENT not respected

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#1073]
v1.11.1-pre26

Node `1` is expected at the same Y offset from `root` as node `2`. Instead it is pushed up by its sibling.

![bug-v11-ChildNodesLayout-position-not-respected-FIRST](https://user-images.githubusercontent.com/7197131/229362199-4395c3fe-2731-4ad7-bc5d-90b2c1e5bdff.png)

[bug-v11-ChildNodesLayout-position-not-respected.mm.zip](https://github.com/freeplane/freeplane/files/11132585/bug-v11-ChildNodesLayout-position-not-respected.mm.zip)

**Comment by macmarrum** [comment]
Similarly in case of LEFT_TO_RIGHT

![bug-v11-ChildNodesLayout-position-not-respected-FIRST-LtoR](https://user-images.githubusercontent.com/7197131/229362622-b1468cae-6c15-474e-8ea6-22fab82fa485.png)

**Comment by dpolivaev** [comment]
Actually it is not a bug.
The map is laid out so that

-  if nodes 1, 2, 3 and 4 are folded, the alignment holds
-  if the user unfolds any node, it position relatively to its parent node does not change.

Therefore unfolding node 3 shifts node 1 up. It makes everything look smooth. Otherwise user would see unpleasant jumps.
