### ISSUE TITLE
Formula or Script Filter `node.isFolded()` provides stale result on fold or unfold

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#1103]
Further to https://github.com/freeplane/freeplane/discussions/1102

Freeplane v1.10.7

Actual
The formula/Script Filter `node.isFolded()` provides an up-to-date state only when the node text is changed (core, details, note) or its child is moved (e.g. repositioned), deleted or added.

Expected
Whenever the node is folded or unfolded, the formula/script filter `node.isFolded()` receives an up-to-date state.

[bug-isFolded.mm.zip](https://github.com/freeplane/freeplane/files/11275317/bug-isFolded.mm.zip)

**Comment by dpolivaev** [comment]
Formula results are cached for filters, conditional styles, and node formulas, and the cache is calculated per map, not per map view.
Until now change of folded status was not removing the calculation result from the cache.
Actually, to get it right I would have to save caches per view because the node folding state is view specific.
Also, I had to propagate information about the folding state change to the cache.

Actually, I am not sure if this bug has a high impact on Freeplane usability I and I would rather not fix it.
