### ISSUE TITLE
in (1.11.x): the unfolded node is moved away out of  the screen, to keep the selected node in the screen

### ISSUE THREAD

**Issue by Bricklam** [freeplane/freeplane#1188]
**Describe the bug**

in (1.11.5_pre01) and all (1.11.x) version:
when I select a node and go unfold another different node (other than the selected one) using the mouse: (by clicking on the folding symbol):
I expect the map view to be focused on the (unfolded node) and NOT the (selected node)
(this was the typical behaviour in 1.10.6 version) and prior ones.
  but in the latest versions (1.11.x):
when I do the same thing: (unfolding a node that is not selected):
the unfolded node is moved away (out of the view), in order to keep the selected one in the screen,
So, the focus stays on the selected node, instead of the node that receive the usere's input (interaction).

I think this is a buggy behaviour. since the correct thing is to keep the focus on the node that the user interact with
even if it is not selected. (like the previous versions)

Note: I thought that these options in the preferences maybe associated with this bug and disabled them,
 but the bug still happens & made no difference at all:

Preferences > Behaviour:
- Zooming keeps selected node position: (OFF)
- Zooming keeps selected node visible: (OFF)

**To Reproduce**
- in the uploaded test map: select the second last node in the list, and go to unfold/fold the last one in the list
you can see unfolded node is moved away (out of the  map view).
you can see all the details in the videos

- here is the test map:
[TEST_44.zip](https://github.com/freeplane/freeplane/files/11607153/TEST_44.zip)

- here is a video shows the normal/expected behaviour (in version 1.10.6_u1)
https://github.com/freeplane/freeplane/assets/129968602/fd4225ba-dbe1-4ac6-bf42-9e4fcf4a8ec8

- and here is a video shows the bug (the bad behaviour) (in version 1.11.5_pre01)
https://github.com/freeplane/freeplane/assets/129968602/1206e05e-09ae-4e8d-8f52-c683ab17ac42

**Comment by dpolivaev** [comment]
I do not understand why you do not like the current behavior: the recent versions keep selected nodes in the viewport after unfolding any nodes if they are in the viewport before because all editing actions are applied to selected nodes and I find it important to keep them inside the visible part of the map.

See discussion https://github.com/freeplane/freeplane/discussions/1190 which is actually old, but because it was opened at the wrong project nobody noticed it until now. I have just moved it to the right project.

Please give your arguments there.

**Comment by Bricklam** [comment]
thanks. I read the discussion and I understand your point. I posted my reply there.
