### ISSUE TITLE
Multiple nodes selection using the mouse (CTRL+Click and drag)

### ISSUE THREAD

**Issue by sifran-github** [freeplane/freeplane#1218]
Ability to select multiple nodes by using the mouse.
Can be implemented like SimpleMindMap: holding CTRL and then pressing and dragging creates the selection rectangle that will select every node that it touches:

https://github.com/freeplane/freeplane/assets/5730355/196329ba-a823-4f3c-a92e-227f28524cfe

**Comment by MarkJeronimus** [comment]
I like to request the same, but with left mouse button without modifier, like how selection works in most other programs. Similarly, panning around by pressing the middle and/or right mouse button like in most other programs.

**Comment by euu2021** [comment]
+1
this is my most wanted feature since my day 1 of Freeplane

**Comment by LSDog** [comment]
+2

**Comment by Jackyttl** [comment]
+3

**Comment by liang0802** [comment]
+4

**Comment by guoranjun2** [comment]
If this requirement is to be implemented, considering users' long-standing habits, I believe it’s important to maintain compatibility with the original operations: using the left mouse button for dragging the page and Ctrl + left-click for selecting nodes within a range. Additionally, if users prefer to select nodes within a range using only the left mouse button, it would be beneficial to add a corresponding configuration option.

**Comment by dpolivaev** [comment]
Ctrl + left-click
Preview 1.12.7_03
https://sourceforge.net/projects/freeplane/files/freeplane%20preview/

**Comment by euu2021** [comment]
> Ctrl + left-click Preview 1.12.7_03 https://sourceforge.net/projects/freeplane/files/freeplane%20preview/

Perfect!

**Comment by nnako** [comment]
works fine. Thanks @dpolivaev .

But what about configurability? As @MarkJeronimus mentioned, there are quite a bunch of applications that use the mouse-driven multi-selection feature in the following way:

- `<LCLICK> + <MOUSEMOVE>`, starting on a free spot (without further modifier)

then the "normal" panning could go to

- `<RCLICK> + <MOUSEMOVE>`, as this combination is not set, yet. and open context menu still works with tipped `<RCLICK>` . so, this would move away from Freeplane's default `<LCLICK> + <MOUSEMOVE>` for panning.

would it be possible to adjust this feature so that this could be achieved?

**Comment by nnako** [comment]
and maybe another thing (to sum it up for me)...

in most applications, it is possible to add nodes to the current selection. In Freeplane, this could (and still can) be done using `<CTRL> + <LCLICK>` on a respective node. This would additionally be nice:

- `<CTRL> + <SHIFT> + <LCLICK> + <MOUSEMOVE>` to add further nodes from a new rubber band selection

or just

- `<SHIFT> + <LCLICK> + <MOUSEMOVE>` when being in the alternative mode (mentioned above)

**Comment by dpolivaev** [comment]
On MacOS and Linux, right-click opens a popup menu and so cannot be used for panning or selection. I aim to maintain a consistent user experience by avoiding changes to long-established behavior. If you would like me to support other options, please explain your use cases so I can evaluate whether the so-called rubber band selection justifies such disruptive changes.

On the contrary, I consider pressing the control key a minimal requirement, given that keyboard input is essential in mind map editing.

**Comment by dpolivaev** [comment]
I can activate rubber band selection on right-cllick on Windows, on commabnd+left-click on MacOS

**Comment by euu2021** [comment]
> On MacOS and Linux, right-click opens a popup menu and so cannot be used for panning or selection. 

Isn't it the same on Windows? 
Also, how those platforms deal with the right-mouse-click drag on a node (which creates a connector between nodes). Isn't it a similar situation? Because, FP needs to differentiate between a single click and a click and drag.


I created an Autohotkey script that does the trick:

```
~RButton::
    KeyWait, RButton, T0.2
    if ErrorLevel {
        Send, {Ctrl down}
        Click down left
        While GetKeyState("RButton", "P") {
            Sleep, 10
        }

        Click up left
        Send, {Ctrl up}
    }
return
```

The negative side effect is that I lose the right-mouse-click drag on a node (which creates a connector between nodes) that I mentioned above, because AHK doesn't know if I'm right-clicking on a node or on the background.

**Comment by sifran-github** [comment]
A bit late but I just want to say thank you for adding this feature. it is very helpful. 👏
