### ISSUE TITLE
a feature request to preserve line breaks (newlines) inside the attribute value text, to be able to store multi-line text inside the attribute values

### ISSUE THREAD

**Issue by Bricklam** [freeplane/freeplane#1241]
**the use case:**
I want to be able to save a plain text inside Freeplane and retrieve it without any change.
the problem with saving plain text inside nodes (non-html or plain text nodes): it can cause some changes to the space characters in the text:
for example: it will trim some trailing spaces or convert the white space into non-breaking spaces: "&nbsp" to able to save them inside the rich content tag in the XML file

that is why using attributes is the best option
because the main advantage of saving plain text inside attributes: it preserves all the spaces within the text (including the trailing spaces) without changing or converting them.
the only downside is:
it cannot preserve line breaks, and usually converts all the line breaks into spaces.
(any multi-line text will be converted to one-line text)

So, my request is to preserve the line breaks in attribute value key, instead of replacing them with spaces.
And at the same time: in order to avoid clutter inside Freeplane attribute window:
keep displaying the multi-line text as one line text (dipslaying spaces instead of line breaks) 
(ignoring and hiding the line breaks inside the attribute window, to avoid cluttering the window)
But if the text is copied out/exported from Freeplane: the line breaks should be present

**what I mean in more details:**

-- when any multi-line plain text is copied into the Attribute Value: the line breaks should be preserved (by converting them to "\&#xa;" code for example, which is the same character used to represent line break in the plain text nodes)
So in the XML file: the "\&#xa;" code will be used to mark the line breaks in the text (just like plain text nodes with multi-lines text)

-- and when the attribute text is viewed/displayed inside Freeplane: it should be displayed as one line (the line breaks displayed as spaces)
(just like it does now), and this is good behaviour to avoid clutter (since the attribute window has a limited text field. So it is better to display the text in one line)

-- but when the attribute text is copied out/exported from the Attribute (value) and then pasted into a text editor: then, the original line breaks should return.
(by converting this code representing line break: "\&#xa;" (written in the attribute text), into an actual line break characters: "\r\n" for windows or "\n" for linux)

and this approach is very similar to saving line breaks in plain text nodes with multi-line text
 (the only difference is: in plain text nodes with multi-line text:
the line breaks is displayed clearly inside the node text because there is a room for it, while in the attribute window there is no need to show them until the user copy/export the text out),
then the line breaks can appear

Note: I added this code into the attribute text in the XML file: "\&#xa;" to create a line break inside the text, but when I checked the text inside Freeplane, I found that this code is not interpreted as line break. instead: it was converted to a white space (unlike the case with the plain text nodes)

Thanks

**Comment by dpolivaev** [comment]
I have checked where line break is replaced by a space.
It happens at the moment when you try to edit the attribute value and it is not reversible because the editor replaces line break by a space and it is recognized as a change and persisted.
If you don't edit the value the line break is kept.

The easiest solution to avoid the change is to disallow editing of values containing line breaks because they can only be created using scripts.

Alternatively, I could use another editor for such values, namely the save as used for formulas.
But I am not sure how far I should go in the treatment of the edge use cases.

**Comment by macmarrum** [comment]
@Bricklam While testing #1231, I found out that when node format is set to Markdown, its content is saved as is, keeping line breaks.
If you care about how the text is displayed, you can surround it with triple backticks, e.g. ` ```content``` `

**Comment by dpolivaev** [comment]
I do not understand the actual problem. Instead of clarifying what you actually need you try to find different solutions. But all of them seem not easy to implement and are quite an edge cases.

For the moment I disabled editing and enabled copying of attributes containing line breaks so that you can access them using scripts.

**Comment by dpolivaev** [comment]
I can implement the logic from the script as an option so that Freeplane opens links in the other view if it is available.

However, if you use view 1 for navigation and view 2 for selection and click on a link in view 2 it would open the link in view 1, and it is probably not what you want. What you actually want is that all links to be opened on view 2.

I can add a menu item to mark views as views for links to be opened. But I do not know how to explain it to any other user.

So, unless we find a solution with documentation implementing this feature seems to be not the right thing to do because it would just confuse most people.

**Comment by dpolivaev** [comment]
Sorry, wrong thread,

**Comment by Bricklam** [comment]
Sorry, I really apologize for this inconvenience. I didn't realize that the attribute editor always replaces the line breaks. I wrongly assumed that the code that handle the attribute (value) text doesn't predict/consider users to add multi-line text into attributes, predicting the users to insert short text to the attributes.
but anyway: this is a trivial issue and. it is really an edge use case and doesn't deserve much time or effort to be changed. you can totally ignore it
Thanks

**Comment by macmarrum** [comment]
> For the moment I disabled editing and enabled copying of attributes containing line breaks so that you can access them using scripts.

A good idea :+1: 

I have tested it (from git). I like the segregation of the copy operation on Attribute Table. `Ctrl+C` now works separately for key and for value, i.e. copying cells rather then whole rows :rocket:

**Comment by dpolivaev** [comment]
Available as described in preview 1.11.5_11
