### ISSUE TITLE
Freeplane misinterpreting text - resulting in run-on misspellings

### ISSUE THREAD

**Issue by kenfhill84083** [freeplane/freeplane#1247]
**Describe the bug**
Using theWord Bible software, I copy to the clipboard a Bible passage from the New American Standard Bible translation (NASB 2020).  After tweaking the verse numbers to italics in Atlantis word processor I paste that text into LibreOffice Writer - where I break the text apart into rough phrases based on punctuation.  At each step so far, I run it thru the spell checkers of Atlantis and LO Writer -  no misspellings. 

In Freeplane, I paste the text and visually see jammed-together "words" where 2 or more words have been smooshed together into one "word".  I copy that branch back into either of my word processors and run spell checks again - confirming the text is riddled with these run-on "words".

**To Reproduce**
1. open new map
2. paste text (previously copied from word processor)
3. many spelling errors of run-on "words"

**Expected behavior**
No run-on "words" because the text was properly recognized in 2 word processors.

**Mind map file**
attached

**text files**
from LO Writer (ODT) and Atlantis word processor (RTF).  I can save as different format if that would be better.

**Desktop (please complete the following information):**
 - OS: windows 11 home
 - Version: 22H2
 - Java Version: 17 0 7
 - Freeplane: Freeplane-Setup-1.11.5-pre12

**Additional context**
Considering that before Freeplane gets the text it is error free, I'm left thinking there is something in FP that is misinterpreting the text.  

One factor may be that NASB shows Old Testament quotations in upper case.  Most of the run-on "words" are in OT quotations but not all are.

[freeplane _ spelling errors upon loading NASB Bible text (MM).zip](https://github.com/freeplane/freeplane/files/11790136/freeplane._.spelling.errors.upon.loading.NASB.Bible.text.MM.zip)
[freeplane _ spelling errors upon loading NASB Bible text (text files).zip](https://github.com/freeplane/freeplane/files/11790137/freeplane._.spelling.errors.upon.loading.NASB.Bible.text.text.files.zip)

**Comment by kenfhill84083** [comment]
> One factor may be that NASB shows Old Testament quotations in upper case. Most of the run-on "words" are in OT quotations but not all are.

I just realized that the non-OT errors seem to follow italicized words - put in by the translators to indicate an English word for which there is no underlying Greek word.

So maybe there is some tagging going on that FP is sensitive enough to catch but my word processors don't.

**Comment by macmarrum** [comment]
During my attempts to test 
- #1231

I was reminded that the content of the clipboard can have different flavors, e.g. plain text, rich text like HTML or others.

I know that when pasting, Freeplane searches the content provided by the clipboard for a flavor that it can understand. So when HTML flavor is available, the HTML from clipboard is converted to what SimplyHTML can handle.

I also noticed that Freeplane is able to preserve the original HTML if it's pasted to a Markdown node. I've created scripts to extract and paste the clipboard HTML:

- [pasteToCore.groovy](https://raw.githubusercontent.com/macmarrum/freeplane-scripting/main/src/scripts/pasteToCore.groovy)

@kenfhill84083 Could you please create a new node, change its Format to Markdown (in `View->Controls->Tool panel` > Core text > Format), then use the script to paste the **_clipboard HTML_**. 

When I do it, I can see that the HTML provided by LibreOffice lacks a space between e.g. `IN` and `ZION`. There are lots of html tags, but no space between the words.
This tells me that the issue is somewhere else than Freeplane. Perhapse in LibreOffice, which produces incorrect HTML representation of the rich text. Or maybe in Java itself.

**Comment by kenfhill84083** [comment]
> @kenfhill84083 Could you please create a new node, change its Format to Markdown (in `View->Controls->Tool panel` > Core text > Format), then use the script to paste the **_clipboard HTML_**.
> 
> When I do it, I can see that the HTML provided by LibreOffice lacks a space between e.g. `IN` and `ZION`. There are lots of html tags, but no space between the words. This tells me that the issue is somewhere else than Freeplane. Perhapse in LibreOffice, which produces incorrect HTML representation of the rich text. Or maybe in Java itself.

I created a new map and a child node, which I changed to "markdown".  Then ran the script.

It put the whole passage in one node.  I want each line of the passage to be a node.  There also is a bunch of HTML code at the top.  The run-ons are still there.  (I tried to include a screenshot but that didn't work.)

I had no idea word processors pollute the text with HTML codes.  A little research indicates LO Writer is not the only one. 

I think you must be correct that the culprit is LO bloating the text.

After more experimenting with Atlantis word processor, I think I will stick to that, although it is more hands-on to break apart into rough phrases.  So far, Freeplane has not choked on text pasted from Atlantis.

Sorry I didn't do more research before throwing out assumptions.

Thanks for your usual, responsive, extra-mile help.

I am closing this post.
