### ISSUE TITLE
FP 11.5_15: cannot load some accelerators

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#1281]
**Describe the bug**
When installing FP 11.5._15, FP misses the accelerators, when you load the former accelerators  you do not have them loaded
You will see the no action label instead of the accelerator short description, but when you hover with the mouse on the key you have the label of the expected accelerator for that key.  In any case, the key doesn't run the accelerator.

**To Reproduce**
see the attachment

**Expected behavior**with loading the accelerators to have them available and readable

**Mind map files**
it happens in all of the maps

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] w11
 - Java Version FP java

**Additional context**

![Screenshot 2023-06-30 154637](https://github.com/freeplane/freeplane/assets/62674157/8f7d4a4f-3ab6-430a-aab6-9561d419e89b)

**Comment by Illegit** [comment]
I add that from my point of view this behavior is really strange: some accelerators have been changed and others not as I described above
[2023-06-29.zip](https://github.com/freeplane/freeplane/files/11917272/2023-06-29.zip)
I loaded here the last accelerators with some that failed to be loaded (see screenshot)
if you compare the 2 screenshots you will see they refer to 2 different set of accelerators, but for example the no style was already in both, and in the first 6/18) you have it and in the second (6/29) not.
Here you have both of the sets.
![Screenshot 2023-06-30 162155](https://github.com/freeplane/freeplane/assets/62674157/19e720f5-ebec-4e5a-859e-fa25d07c28c0)
[2023-06-18.zip](https://github.com/freeplane/freeplane/files/11917338/2023-06-18.zip)

**Comment by Illegit** [comment]
last check: only from F9 to F11 they were missing styles (not replaced by the map), for the rest instead they are all existing commands/style/etc.

**Comment by dpolivaev** [comment]
I have checked what is wrong with F7 and have two findings:

In the attached property files there are two conflicting lines where F7 is assigned.

````
acceleratorFor.MindMap/CopyStyleExtensionsAction=F7
acceleratorFor.MindMap/addons.gtdSyncWithTodoTxt.NextAction_on_selected_node=F7
````

The second line tries to overwrite the first line, and if the action specified in the second line is not found, it assigns `"<no action>"`.

The only bug I found was that the tooltip was not properly reset, and I am fixing it now. After the fix the tooltip will no longer be shown.

In the past Freeplane was ignoring accelerators if the actions were not available. Therefore it allowed to store more than one action per accelerator assuming that some of them could not be available. It could happen if hot keys are assigned to styles, and then keeping more than one action per hot key would make sense. But the logic has not differentiated between style actions and other actions.

@macmarrum expressed an opinion that this  logic does not match his expectations, and I removed this part from the code. Therefore in preview 1.11.5_15 the accelerator was not available. The tooltip was not properly removed, and it was indeed confusing.

Because @macmarrum opened a new discussion about changes in hot key behavior, I am reverting my change so that in the coming stable release Freeplane works as before and we can discuss all changes before I implement them.

See https://github.com/freeplane/freeplane/discussions/1267.

**Comment by dpolivaev** [comment]
Actually I find the title of the issue "FP 11.5_15: cannot load the accelerators" probably incorrect. It should be "FP 11.5_15: cannot load SOME accelerators"

**Comment by Illegit** [comment]
Yes you are right, I discover it gradually.

**Comment by dpolivaev** [comment]
Preview 1.11.5_16
