### ISSUE TITLE
1.11.5 changed the behavior of Enter+Paste: For new child nodes paste should go inside the new node

### ISSUE THREAD

**Issue by sigmike** [freeplane/freeplane#1326]
**Describe the bug**
In version 1.11.4 when I pressed "Enter" to create a new sibling node and then "Ctrl+v" to paste, the copied content was put inside the new sibling node.

In version 1.11.5 when I do the exact same thing the copied content is put inside a new child node of the new sibling node.

I can fix that by pressing F2 after Enter, but it's an additional keystroke.

Is that an intended change? I don't see that mentioned in the history file.

**To Reproduce**
1. Copy some text
2. Create a new map
3. Add a new child node
4. Add a new sibling node
5. Press Ctrl+v

**Expected behavior**
The copied text should appear in the new sibling node.

**Desktop (please complete the following information):**
 - OS: Linux
 - Java Version: 20, I think

**Comment by Doemaas** [comment]
This also happens on macOS Ventura 13.5.
Further comment at step 5: when start typing text, that text will be put in the sibling node as you would expect.
So, my workaround now is type a letter other than space (space will open/close the tree starting at that node but because of it being a single node nothing happens), then backspace and then Cmd-v. Which is 2 extra actions that were not needed in previous versions.
My steps to reproduce: at any node, Cmd-Tab (to insert a new child node), Cmd-v (generates new child nodes on that first empty child node)
Expected:  at any node, Cmd-Tab (to insert a new child node), Cmd-v (puts the content of the clipboard into the child node)

**Comment by theelectricsoul** [comment]
OS: Windows 10

I tested some preview of 1.11.5 and it worked normally. 

Then I tested 1.11.5 pre-19. It also happens there.

https://github.com/freeplane/freeplane/assets/10260832/04180a79-797a-4f11-9cb7-766baa9e55c9

**Comment by dpolivaev** [comment]
Preview 1.11.6_01
https://sourceforge.net/projects/freeplane/files/freeplane%20preview/
