### ISSUE TITLE
Key reference table is unreadable while using built in dark themes

### ISSUE THREAD

**Issue by Furgelnod** [freeplane/freeplane#1386]
**Describe the bug**
The key reference table is improperly styled when using any of the inbuilt dark themes.

**To Reproduce**
Tools > Preferences > Appearance > Look and feel > Set this to any of the dark themes (Atom One Dark Contrast (Material) | Flat Dark | Flat Dracula)
Then
Help > Key reference
The table is difficult to read.

**Expected behavior**
The style of the list should be adjusted so that there is adequate contrast.
There should be specific style for the dark mode themes as in the about box or the content background colour should be manually set to be white in this window.

**Screenshots**
![Screenshot 2023-09-07 000120](https://github.com/freeplane/freeplane/assets/6347198/4de51309-adc1-476c-a116-939b247e5e3b)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Version [e.g. 22] 1.11.6
 - Java Version Liberical JRE 17.0.8

**Additional context**

**Comment by macmarrum** [comment]
@Furgelnod 
Here's an alternative way of listing the hot keys, i.e. as a mind map:
- [createHotKeyMindMap.groovy](https://raw.githubusercontent.com/macmarrum/freeplane-scripting/main/src/scripts/createHotKeyMindMap.groovy)

You can download the script and save it in your `<user-dir>/scripts` (can be easily opened via `Tools->Open user directory`).
You need to restart Freeplane for new scripts to be recognized.

You'll find the script in `Mac2->Create Hot Key Mind Map`. To have it appear in `Tools->Scripts`, remove `="/menu_bar/Mac2"` from the first line.

@dpolivaev 
It might make sense to include this option in Freeplane core, or even replace the HTML-table reference. I never liked it, because I cannot search in it or sort it, etc.
What do you think?

**Comment by dpolivaev** [comment]
I would recommend using the command search dialog also for searching command shortcuts.

In the script, I would use 

````
def mindMap = c.newMindMap()
def hotKeyRoot = mindMap.root
hotKeyRoot.childNodesLayout = ChildNodesLayout.TOPTOBOTTOM_RIGHT_FLOW
hotKeyRoot.text ='Hot Keys'
````
instead of `MenuUtils.executeMenuItems(['NewMapAction'])`

I am not sure if we should add the script to the standard distribution.

**Comment by dpolivaev** [comment]
Preview 1.11.7_02
https://sourceforge.net/projects/freeplane/files/freeplane%20preview/
