### ISSUE TITLE
Some error log only

### ISSUE THREAD

**Issue by doctomlug** [freeplane/freeplane#1407]
As I am not sure when the error popped up, I can provide the log only. 
Maybe it helps anyway, otherwise delete the posting.

Several larger maps open, just folding / browsing through them, no editing done.
Version 1.11.7v02 portable install

Interestingly I got no error report pop up although the policy setting is "Show report dialog" (sound is muted)

[log.zip](https://github.com/freeplane/freeplane/files/12618964/log.zip)

**Comment by dpolivaev** [comment]
Thank you for reporting. The error is reported from a library that is not maintained any longer, and I also do not know how to reproduce it.

The report pop-up is not shown if the bug report having the same stack trace has already been sent from the currently running Freeplane version because in this case the bug report is not sent either.
