### ISSUE TITLE
Zooming the text inside in RTL languages

### ISSUE THREAD

**Issue by dpolivaev** [freeplane/freeplane#1521]
When few words are written, when zooming the text inside the node gets messed up. It works correctly in 100% zoom.
I don't know why it works correctly in English, but the right-to-left language messes up the text at zooms higher or lower than 100%. I didn't have such a problem before.
It can be said that Freeplan is compatible with right-to-left languages, but this problem is annoying in large maps.
 

[zoom.zip](https://github.com/freeplane/freeplane/files/13296614/zoom.zip)

_Originally posted by @ajaberi1360 in https://github.com/freeplane/freeplane/discussions/1518#discussioncomment-7510034_

**Comment by aaa1386** [comment]
I found a workaround:
The default node settings should be set as shown below, always a very small minimum value of the node width is less than the maximum.


![image](https://github.com/freeplane/freeplane/assets/38586259/612da03a-c7d0-4f74-bacc-7d9d33d3a16a)

**Comment by aaa1386** [comment]
There are still errors, sometimes the error is not solved by reducing the minimum width of the node. In addition, this error also exists for the selected node style.
This error does not exist for the English language.
See the mind map below

**Comment by aaa1386** [comment]
[BUG 2.zip](https://github.com/freeplane/freeplane/files/13311132/BUG.2.zip)

**Comment by aaa1386** [comment]
See the following video:

I set the maximum width size and minimum width size of the two right nodes equal to the maximum and minimum for the selected node style.

https://github.com/freeplane/freeplane/assets/38586259/21314f18-e3f2-4484-a428-fd07207e7389


It seems that this errors is due to the fact that the border node, whether it is thick or thin, reduces the width and length of the node.
Node Border and node dimensions must be independent of each other.
When we increase the border node, it should not decrease the length and width of the node.

[BUG---.zip](https://github.com/freeplane/freeplane/files/13318306/BUG---.zip)
