### ISSUE TITLE
Links to folders on Windows open in Explorer rather than default file browser

### ISSUE THREAD

**Issue by steveatmaat** [freeplane/freeplane#1669]
**Describe the bug**
Probably not a bug, maybe a setting I'm not aware of.
If I have a link to a Windows folder in a node or a note, clicking on it opens the link in Windows File Explorer, rather than the replacement file browser, xploerer2, that I have set up to replace Windows File Explorer. I have only noticed this in versions 1.11.5 and later.

**To Reproduce**
Install xplorer2 ("xplorer squared) by Zabcat. Set it to replace File Explorer for all users
In a node or note create a link to a folder.
Click the link.
The folder opens in Windows File Explorer, not xplorer2.

**Expected behavior**
The folder opens in xplorer2.

**Mind map files**
If possible, upload a zipped mind map file where the problem occurs.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Edition
 - Version Freeplane 1.11.5 and later
 - Java Version: the Java version included in the Freeplane install

**Additional context**

**Comment by i-plasm** [comment]
Hello @steveatmaat , Freeplane latest versions uses the `Desktop` class for handling browsing of resources, which typically will use the default Windows File explorer for opening folders. I wrote a script [(openDirectoriesWithUserExplorer)](https://raw.githubusercontent.com/i-plasm/freeplane-scripts/main/src/scripts/openDirectoriesWithUserExplorer.groovy) that is similar to Freeplane's old way of browsing, and it will generally work for opening the Folder with the user's preferred explorer.  Note that some permissions need to be set on `Tools -> Preferences -> Plugins -> Scripting`- check the script header for details. Installing new scripts and changing permissions require a Freeplane restart. If it works for you, I suggest assigning a shortcut for convenience (`Tools > Assign hot key`). Hope it helps.

**Comment by steveatmaat** [comment]
The suggested script solved the problem.

**Comment by walmar** [comment]
I would describe the well-explained script of i-plasm rather as a  partial workaround for a regression than a real solution for the changed behavior of file manager-related software like QTTabBar, which is no longer called via FollowLinkAction or OpenCurrentMapDirAction.

There also seems to be another report about this type of problem: [DirectoryOpenException: Program Blocking · Issue #1535 · freeplane/freeplane · GitHub](https://github.com/freeplane/freeplane/issues/1535)

The issue appears to me since commit [@41ff017](https://github.com/freeplane/freeplane/commit/41ff0177e5c9f61d0930d6c0554010ffba4902f3).

The script approach lacks security and flexibility, for example when someone wants to open the map directory in preferred software via a toolbar button.

**Comment by walmar** [comment]
Dear @steveatmaat,
could you please consider reopening the issue so that @dpolivaev as a developer can decide on topic closing?

**Comment by steveatmaat** [comment]
At the request of @walmar I am reopening this issue so that @dpolivaev as a developer can decide on topic closing.
The script offered by @i-plasm works well for me, and the possible security issues are not a priority for me, but I do think that the issue may deserve further discussion.

**Comment by walmar** [comment]
It seems to me as I have to write a tricky AutoHotkey script for a full workaround to open folders via mouse button and for my custom OpenCurrentMapDirAction toolbar button that includes the given script approach before I can update from Freeplane1.11.7-pre02. Since the developer has not yet responded to the reported regression.

The AutoHotkey script generally wouldn't be the first one that I have to use to work around a reported software regression. So it seems to me this kind of situation is more and more common these days.

**Comment by dpolivaev** [comment]
For me it is not a regression. The new behavior uses standard Java methods. The old implementation failed on folders containing non ascii characters. I generally avoid introducing new options because I do not believe in users ability to discover them. Therefore I am currently not going to work on this issue.

**Comment by macmarrum** [comment]
This is how I've made Freeplane to open directories in Double Commander.

Based on the advice from https://superuser.com/questions/1031250/replace-windows-explorer-as-default-file-viewer-in-windows-10, I've created the following .reg file and executed it.

```reg
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Drive\shell]
@="open"

[HKEY_CLASSES_ROOT\Drive\shell\open\command]
@="\"C:\\Program Files\\Double Commander\\doublecmd.exe\" -c -t \"%1\""

[HKEY_CLASSES_ROOT\Directory\shell]
@="open"

[HKEY_CLASSES_ROOT\Directory\shell\open\command]
@="C:\\Program Files\\Double Commander\\doublecmd.exe -c -t \"%1\""
```

Now any directory is opened by Windows in Double Commander, not only from Freeplane but from ohter apps too.

@walmar 
I don't know QTTabBar, but I can imagine that the soluton – being generic – should work for QTTabBar too.

**Comment by walmar** [comment]
Based on https://github.com/freeplane/freeplane/commit/41ff0177e5c9f61d0930d6c0554010ffba4902f3#diff-cb8e996241341e9564dcd83ba1ff3f182142d18ed024d55c654234558b6d28a1L42, the comments by @i-plasm and @macmarrum and my testing with Freeplane 1.11.13 and the Windows Explorer extension QTTabBar 1043 on Windows 7, it seems that executing a .reg file as administrator with the following content is necessary in order to open drives and folders through programs with the default file manager-related software on Windows OS.

````reg
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\shell\open]

[HKEY_CLASSES_ROOT\Directory\shell\open\command]
@="rundll32 url.dll,FileProtocolHandler \"%1\""

[HKEY_CLASSES_ROOT\Drive\shell\open]

[HKEY_CLASSES_ROOT\Drive\shell\open\command]
````
