### ISSUE TITLE
FP 1.11.11.01: shortcuts do not work any longer

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#1681]
**Describe the bug**
1) many shortcuts do not work with this new release.
2) even the Menu-o-Matic doesn't launch the menus as in previous releases (same settings of autolaunch in preferences
3) same problem with Bookmark addon
4) and so on with all shortcuts
I have to activate commands with mouse.

**Desktop (please complete the following information):**
 - OS:W11
 - Java Version as FP version

**Comment by dpolivaev** [comment]
Thank you for reaching out with your concerns about the recent issues you've encountered. Your report is crucial for identifying potential improvements; however, as the solo developer of this project, my expertise is primarily focused on the core functionality of Freeplane. I must admit that I'm not familiar with the Menu-o-Matic extension or the Bookmark addon, as these are not components I've directly worked with or developed.

To better assist you and understand the scope of the issue, could you please provide the following information?

Specific Shortcuts or Features Affected: Clearly identify each shortcut or feature that is not working as expected, especially if these are part of the core application or linked to third-party extensions.
Detailed Description of the Issue: For each identified shortcut or feature, please describe what you are experiencing versus what you expect to happen.
Environment Details: Your operating system, the version of Freeplane you are using, and any relevant information about how you installed or are using the Menu-o-Matic extension and Bookmark addon.
Additionally, since my expertise with these extensions is limited, I recommend reaching out to the developers or support communities associated with Menu-o-Matic and the Bookmark addon for specific guidance on installation and troubleshooting. They may offer more direct insight into resolving issues related to their products.

I understand this situation may be frustrating, and I appreciate your patience and willingness to provide further details. Your input is invaluable for enhancing Freeplane's usability and for supporting its diverse user base.

Thank you for your support and understanding.

Best regards, Dimitry

(written with assistance of ChatGPT)

**Comment by Illegit** [comment]
Ok Dimitry, 
I share this not to blame but only if it would be helpful to you in some way:
after the FP 1.11.11_01 when re-installed the 1.11.10 was stable, (reinstalling an FP release on another FP release before, it was working always) but after this last installation FP was launching the splash but never reacted and I couldn't open FP.... at the end, after a few trials I needed to un-install FP (1st time in years) to copy all of the 1.11.x files from another installation and re-install the FP 1.11.10 stable, now it is working but it took to me a lot of time to recover this topic. 

Therefore I'll try to re-create this error again this weekend at best...

**Comment by dpolivaev** [comment]
I have already got a bug report that the latest Freeplane version can not start if the file CodeExplorer.json in the user configuration repository is empty. If it is this problem, there is a characteristic exception in the log file.

See https://github.com/freeplane/freeplane/issues/1678

**Comment by Illegit** [comment]
ok got it in the we I try again the shortcuts issue.

**Comment by Illegit** [comment]
[log - Copia.zip](https://github.com/freeplane/freeplane/files/14231786/log.-.Copia.zip)
Hi Dimitry, here is my log file, there are a lot of error... any suggestion?
Again I installed the FP 1.11.11_01 and now shortcuts are working, but again even the addons of EdoFro didn't start Tabbed Panel (about this I'll contact EdoFro)

Thanks

**Comment by Illegit** [comment]
Just now when restarted with FP 1.11.10 stable I got the same error with codeExplorer.json of 0 value and I copied inside the older version (as you suggested, but not just deleting) and FP 1.11.10 is working correctly and even the addons above cited.

**Comment by EdoFro** [comment]
> [log - Copia.zip](https://github.com/freeplane/freeplane/files/14231786/log.-.Copia.zip) Hi Dimitry, here is my log file, there are a lot of error... any suggestion? Again I installed the FP 1.11.11_01 and now shortcuts are working, but again even the addons of EdoFro didn't start Tabbed Panel (about this I'll contact EdoFro)
> 
> Thanks

I had no problems with the new version and my addons. More info [here](https://github.com/EdoFro/Freeplane_Menu-o-Matic/issues/17#issuecomment-1939163536).

BR

Edo

**Comment by dpolivaev** [comment]
Could you please upload zipped file:/C:/Users/excel/AppData/Roaming/Freeplane/1.11.x/icons/Music/Chords_w.svg ?

**Comment by Illegit** [comment]
Sorry not any longer because it was blocking everything of FP and I have deleted that file. Normally it happened before that if a svg file is not readable (as in this case) FP doesn't start. What is not clear is why it happened with FP 1.11.11_01 and not with 1.11.10 stable or previous ones...
Previously it happened that I created svg with some simple apps and they were not readable in any case, and they blocked FP. But this one has been corrupted in the recent past... in any case, even if corrupted FP1.11.10 was working and FP 1.11.11_01 was not.
After deleting it Fp is working .
