### ISSUE TITLE
Detect when a file has changed and reload it

### ISSUE THREAD

**Issue by balta2ar** [freeplane/freeplane#170]
I run two instances of freeplane: one on my work machine, another one on my home machine. They share/read the same files that are synced over dropbox-like service. It would be nice if freeplane could detect that a file has changed externally so that it would offer to reload it, or maybe even do that automatically if there are no conflicts.

**Comment by acebone** [comment]
What would be really nice is if the file was not reloaded, but a diff between the file and the map in memory was made, and new nodes just added ... live.

**Comment by melvincarvalho** [comment]
This seems to be implemented now, which is brilliant!

https://sourceforge.net/p/freeplane/featurerequests/2543/

However when clicking 'remember my decision' it doesnt seem to work for me

**Comment by melvincarvalho** [comment]
I think this needs to be set:

BOTH_OK_AND_CANCEL_OPTIONS_ARE_STORED

In:

https://github.com/freeplane/freeplane/blob/5368a595f7ac1630e00a176c6009daeeffbdf721/freeplane/src/main/java/org/freeplane/features/url/mindmapmode/ExternalMapChangeMonitor.java#L76

**Comment by dpolivaev** [comment]
The purpose of not storing the OK selection is that the user should always be warned iff the map should be reloaded

**Comment by melvincarvalho** [comment]
@dpolivaev thanks for the response

I'm working on some quite advanced uses of freeplane, towards the idea of collaborative mind maps

This is part of ongoing work in the last 10 years.  Let me show you a short screencast (23s) to give you an idea:

https://www.youtube.com/watch?v=cyvrCu8-0qY&feature=youtu.be

The one feature I desperately need is the ability to reload a map, without an a manual intervention from the user, having to make a number of mouse clicks

I spent much of the last week trying to get gradle working so that I could make a change in my version, but I cant get it to compile yet

To give you an idea, I need this feature so much that ive started a port of freeplane to javascript that will take many years to get even a fraction of the functionality, but the one thing I need is ability to reload

I'm so close to having the freeplane that I would love to use, but also so far away.  Just that one setting change would make all the difference in the world to me

Is there any chance at all that you would reconsider?

**Comment by dpolivaev** [comment]
If you develop anything potentially relevant for the Freeplane user community and need my support you can register at Sourceforge and write a post about it in our community discussion forum https://sourceforge.net/p/freeplane/discussion/758437/. Then we could figure out a solution together.

**Comment by melvincarvalho** [comment]
Thanks @dpolivaev I'm already on that forum, and have posted there in the past

If you watched the video above, you might see it would be impractical to do realtime updates having to click a popup every time something changes

All I need to get my prototypes working, is a way for freeplane to remember my decision, which is already opt in.  I want the reload, and I want the system to remember my decision

But I'm blocked because I cant compile freeplane right now, and from my perspective a change in the codebase would seems a high barrier

I'll keep trying to compile a fork of freeplane, and will ask for some help on sourceforge with gradle plugins, if that's OK

I'll also try and experiment with groovy or js scripts that might be able to reload for me, but I expect it's not going to be possible to remove the popup, but I dont know yet.

**Comment by dpolivaev** [comment]
Many people have managed to compile Freeplane, and if you need support in running Gradle you can post the Gradle output to the forum. If you develop some functionality and don't see a good solution you can also describe it in the forum.
If you want me to revisit your old posts you can send me the links to them here. Then I could probably tell why I have not responded earlier and which possible solutions I see.

**Comment by melvincarvalho** [comment]
@dpolivaev thanks again!

I took your advice and raised a first comment here:

https://sourceforge.net/p/freeplane/discussion/758437/thread/1e31e008c2/

I'll work on gradle this week and raise another one if I still cant get it to work.  Thank you again for your help!
