### ISSUE TITLE
Freeplane can't find Java runtime

### ISSUE THREAD

**Issue by hobson42** [freeplane/freeplane#1857]
**Describe the bug**
When I click the freeplane icon, the program does not start, nor does any error message appear. 
When I type freeplane into a terminal I get - see below. 

**To Reproduce**
1. Open terminal
2. Type freeplane
The result is 
ian@cyllene:~$ freeplane
[warning] /usr/bin/freeplane: No java runtime was found
[error] /usr/bin/freeplane: Unable to find an appropriate java runtime. See java_wrappers(7) for help

**Expected behavior**
Find a runtime and continue to start. 

Clearly  apt install has not checked there was a suitable runtime. 

**Mind map files**
Can't get that far!

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Ubuntu 24.04 
 - 
 - Java Version OpenJDK Runtime Environment (build 21.0.3+9-Ubuntu-1ubuntu1)
 - 

**Additional context**
The fuller log. 
ian@cyllene:~$ sudo update-alternatives --config java
[sudo] password for ian: 
There are 2 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                         Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/jdk-21-oracle-x64/bin/java       352346112 auto mode
  1            /usr/lib/jvm/java-21-openjdk-amd64/bin/java   2111      manual mode
* 2            /usr/lib/jvm/jdk-21-oracle-x64/bin/java       352346112 manual mode

Press <enter> to keep the current choice[*], or type selection number: 1
update-alternatives: using /usr/lib/jvm/java-21-openjdk-amd64/bin/java to provide /usr/bin/java (java) in manual mode
ian@cyllene:~$ java --version
openjdk 21.0.3 2024-04-16
OpenJDK Runtime Environment (build 21.0.3+9-Ubuntu-1ubuntu1)
OpenJDK 64-Bit Server VM (build 21.0.3+9-Ubuntu-1ubuntu1, mixed mode, sharing)

I have purged freeplane and reinstalled. 
I have found java_wrappers - but the files made no sense to me.

**Comment by dpolivaev** [comment]
The entire logic Freeplane uses to find Java on linux is contained in freeplane.sh. As a linux user please investigate what happens and suggest a fix. At the moment I do not have any linux system installed.

**Comment by OM-BDF** [comment]
Hello community,
I am wondering if someone did find a solution for this trouble?

I have exactly the same problem on a Linux Mint 22.1 system. 
I installed Freeplane via apt but it cannot find the JRE. I checked, the JRE and JDK are botth installed.

Any help is welcomed.
Thank you in advance.
Regards

**Comment by walmar** [comment]
Hi OM-BDF,
I'm not a daily Linux desktop user.

However, it seems to me that your request lacks basic background information, such as:
* The Freeplane version you try to run.
* If you have followed [Select Java installation used to run Freeplane - Command-line options and configuration - Freeplane Documentation](https://docs.freeplane.org/getting-started/Command-line_options_and_configuration.html#select-java-installation-used-to-run-freeplane).
* The output of running ``freeplane.sh`` in the terminal, as mentioned by dpolivaev and provided for #1792.

I doubt you'll get more attention unless you put in more effort yourself.

**Comment by OM-BDF** [comment]
Dear walmar,

sorry for having bothering you. How do you know the amount of effort I did put in myself before posting a help message?  I am a bit more than a newbie in the Linux world, but still. If that is a problem for you, please ignore me. If you like to help but need more data, just guide me.

Now, first information you listed, I wanted the latest Freeplane. 

In fact, when I did ask if someone found a solution to this trouble, it is because everything is described in the first message of the thread above.

So, in order to detail a bit more the amount of efforts I put it, I installed it via the GUI software installation app. The icon appears in the menu, but nothing was happening. I removed it using the GUI interface, took my breath and did install it via the command _apt install freeplane_ .
I cannot tell you which one has been installed as it never launched. There was no error screen neither. Nothing.
I also tried to launch it via the Terminal. The only output was that Java was not found.
I run _java --version_, got an answer. I also install the latest JDK, downloaded from the Java website. Removed freeplane and installed it again. Still no success.


Secondly, if I did post the message, it is because I did not find the two links you did provide here and that I came accross this issue thread.
**Thank to you, other people will be able to solve the same problem.**

On my end, as I encounter too many troubles for my work with Mint 22 (Freeplane was not the only software that was not running properly), I decided to scrap everything and went to Debian. I cannot anymore say if these advises will work on Mint or not.
It is a shame as I really did enjoy the feel of Mint. I might go back in the futur when I will have more time for solving this kind of troubles.

Regards
