### ISSUE TITLE
Error caused by interacting with a node with specific core text

### ISSUE THREAD

**Issue by walmar** [freeplane/freeplane#1961]
**Describe the bug**
In attached, zipped mind maps,

- when trying to fold c, edit its child node, or close the map, Freeplane writes the following error lines to the log file:

```
SCHWERWIEGEND: Exception in thread "AWT-EventQueue-0"
java.lang.IllegalArgumentException: TextHitInfo is out of range
```

- when folding p, Freeplane displays the following error messages:
  > Bad node view child components: missing node for component

  > Internal error, program terminates.

**Mind map files**
[mindmaps.zip](https://github.com/user-attachments/files/16566870/mindmaps.zip)

**Desktop:**
 - OS: Windows 7
 - Freeplane Version: 1.11.14
 - Java Version: Eclipse Temurin JRE mit Hotspot 11.0.24+8 (x86)

**Comment by dpolivaev** [comment]
[SimpleSwingApp.zip](https://github.com/user-attachments/files/16569252/SimpleSwingApp.zip)
Check this app. It fails under Windows 10 too when I run it with Java 11.
The text is taken from your example from node c.

**Comment by dpolivaev** [comment]
Generally, emojis are not supported well by Java AFAIK, and I would not spend time on such experiments if I were you.

**Comment by i-plasm** [comment]
@walmar  I noticed  on my tests that the problem is caused, in MindMap1, by the use of the "Sans Serif" font on the child node of node c1, the one with emojis. I removed the error on your map by changing the font of the problematic node to e.g Arial, Tahoma, Comic Sans, and I assume in general the error will not occur with fonts that are actually supportive to emojis. However, the error occurred again if I changed the font to "Serif" and "Monospaced". So I it seems Java has a bug (at least in my environment) when these "logical fonts" are chosen. Hope this helps. P.S Using Windows 10. Info on Java and Logical Fonts: https://docs.oracle.com/javase/8/docs/technotes/guides/intl/fontconfig.html

**Comment by walmar** [comment]
The cases were isolated from much larger mind maps in which I had inserted
1. a HTML link for reference as a bookmark
2. a CommandLine string in HTML of a Firefox based browser process from WMIC command output for documentation

The annoying error can also occur with inserted text from other sources such as emails, messengers or forum posts.

Based on the comment by @i-plasm and my testing with Freeplane 1.11.14 and Eclipse Temurin JRE with Hotspot 11.0.24+8 (x86) on Windows 7, it seems that creating the file `fontconfig.properties` in `JavaHome/lib/` directory (as a renamed copy of the existing `fontconfig.properties.src`), removing all occurences of the substring `,dingbats,symbol` in it using a text editor, and restarting Freeplane is necessary in order to interact without errors with nodes containing specific core text in one of the *logical fonts*.

**Comment by dpolivaev** [comment]
I found a workaround for distributions with embedded java.
Please try https://sourceforge.net/projects/freeplane/files/freeplane%20preview/Freeplane-Setup-with-Java-1.12.7-pre08.exe/download
