### ISSUE TITLE
freeplane opens the files corrupt

### ISSUE THREAD

**Issue by go4-real** [freeplane/freeplane#1981]
**Describe the bug**
Freeplane no longer starts correctly and does not open the files as they were in the original since today

**To Reproduce**

1. start Freeplane 
2. all files are now in the color magenta and not loaded in original and cannot be restored. (see screenshot). All branches, clouds and colorings have disappeared except for the respective root nodes.
3. i have reinstalled Freeplane version 1.11.14 / 1.12.2 / 1.12.3 and 1.12.4u1 for testing - no success!
4. the file names are still there and the file volume in KB still seems to be correct. 

**Expected behavior**
To open the *.mm files correctly like every day

**Mind map files**
If possible, upload a zipped mind map file where the problem occurs.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Windows 11 pro, 
 - Version [e.g. 22] version 23H2
 - Java Version  -  Java8 Update 421 (64-bit)
8.0.4210.9 // 25.07.2024

**Additional context**

Is it possible that FreeMind caused this bug? To have a look, I opened an old file that I had created in FreeMind back then in FreeMind. I did not use or have this file open in Freeplane - but it wasn't the first time that I looked something up in the old FreeMind and nothing unusual has ever happened.

I work extensively with Freeplane every day and have had no problems so far.
It’s my main tool in this phase of our startup - please help, as I have written a large project with various mind maps in Freeplane and now I can no longer pass on my work to the other team. All work is now blocked. What can I do? THANK YOU VERY MUCH FOR HELPING!

![Screenshot 2024-08-20 - freeplane only with root and not opening anymore2](https://github.com/user-attachments/assets/1ae8883a-543e-4ece-aa29-de70a99e414c)
![Screenshot 2024-08-20 - freeplane only with root and not opening anymore-3](https://github.com/user-attachments/assets/f3721284-4073-40f4-b4b1-c5682fa1bf2c)

**Comment by dpolivaev** [comment]
Please upload Freeplane log files (zipped) and ideally some of your mind map files that can not be opened.
I can not debug screenshots.

**Comment by go4-real** [comment]
Hi Dimitry Polivaev - thank you for answering - attached you'll receive the log files and a mind-map zipped.
[2024-08-19.zip](https://github.com/user-attachments/files/16679733/2024-08-19.zip)
[logs.zip](https://github.com/user-attachments/files/16679734/logs.zip)

**Comment by go4-real** [comment]
sorry wrong

**Comment by go4-real** [comment]
now it's re-opened - I apologize for the mishap

**Comment by dpolivaev** [comment]
Thanks, I got your files.

1. Close all Freeplane instances so that no of them is running
2. Create a zipped backup of C:\Users\windy\AppData\Roaming\Freeplane\1.12.x. If you can, send it to me for further checks.
3. Delete the content of C:\Users\windy\AppData\Roaming\Freeplane\1.12.x\auto.properties keeping the empty file in the directory
4. Delete directory C:\Users\windy\AppData\Roaming\Freeplane\1.12.x\scripts\init
5. Delete directory C:\Users\windy\AppData\Roaming\Freeplane\1.12.x\compiledscripts
6. Delete directory C:\Users\windy\AppData\Roaming\Freeplane\1.12.x\addons
7.  Delete directory C:\Users\windy\AppData\Roaming\Freeplane\1.12.x\resources

Now, try to start Freeplane 1.12.4u1, try to open all your mind maps one by one using menu item "File->Open mind map… (Control+O)" and let me know how it worked.

**Comment by go4-real** [comment]
Thank you Dimitry for your instructions... 👍 the problem is, I'm not a dev, only a user and it's scaring for me to delete things I don't understand - I hope you understand my situation - but I can send you the zip of the backup hoping that it's the one you wish. Sorry & thank you very much!
[1.12.x.zip](https://github.com/user-attachments/files/16682108/1.12.x.zip)

**Comment by go4-real** [comment]
Dear Dimitry, I dared to follow your instructions and I'm very happy to tell you, that the first most important MM at the moment seems to be back as I left it yesterday - only the format seems to be missing! THANK YOU AGAIN!

**Comment by dpolivaev** [comment]
I checked your configuration. Your problem was caused by the spotlight setting "Preferences…->Appearance->Activate spotlight by default"

<img width="467" alt="spotlight" src="https://github.com/user-attachments/assets/0d16112a-c35a-4516-8ec5-0bec3f24343f">

Deactivating this option would be sufficient to solve your main problem. So if you like you can restore your original configuration files at their old location.

Additionally, in the log files I see an error because one of your nodes has content `="Thank you" fee  `. Because it starts with character `=`, freeplane tries to interpret it as groovy code and regularly throws exceptions because it is no valid groovy code.

Both issues are no Freeplane bugs.

**Comment by go4-real** [comment]
Dear Dimitry - THANK YOU VERY MUCH FOR YOUR HELP, EXPLANATIONS AND SOLUTION! 
Just one last question, I didn't found in the manual how to restore the files at their old location?
