### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by pmraps** [freeplane/freeplane#2160]
**Describe the bug**
A bell rings and an error is flagged at the bottom of the window

**To Reproduce**
1. Start Freeplane
2. See error

**Expected behavior**
I would expect not to see errors

**Mind map files**
If possible, upload a zipped mind map file where the problem occurs.

**Screenshots**
![startup_error](https://github.com/user-attachments/assets/a6c68220-89a8-44dd-ab65-febda36afb4b)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Windows 10
 - Version [e.g. 22]: 1.12.8
 - Java Version: 21.0.5

**Additional context**
[log.0.txt](https://github.com/user-attachments/files/18217648/log.0.txt)

**Comment by HaaiHenkie** [comment]
Hello @pmraps ,

The problem is not with Freeplane but with the following library:

lib\freeplaneGTD\GtdReportViewController.groovy

It tries to import the Freeplane class org.freeplane.core.ui.components.MultipleImage. Apparently this class has dissappeared. It is not part of the Freeplane API and it is not advisable to only use the Freeplane API when in scripts and add-ons.

You should file a bug to the developer of GtdReportViewController.groovy

**Comment by macmarrum** [comment]
Reported also in #1284

You can try the latest version https://github.com/gpapp/FreePlaneGTD/releases
See also https://www.itworks.hu/portfolio/freeplane-gtd/

**Comment by pmraps** [comment]
@HaaiHenkie , @macmarrum , thank you both, that upgrade seems to have solved it.
