### ISSUE TITLE
Closing map views with the mouse middle button

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#2163]
What: I would like to be able to close a map view by clicking on the tab name with the mouse middle button, like happens in Google Chrome, for example.

Why: sometime I'm in a situation with multiple tabs, like this:

![image](https://github.com/user-attachments/assets/76f18808-a02a-4611-b776-45328eacfd63)

The tab 2 is active, and I want to close tab 3. Currently, I need to activate tab 3, in order to make the X button show up, and only then I'm able to close it. It would be more convenient if I could close tab 3 by clicking on it with the mouse middle button, because I would not need to activate it first.

Thanks,

**Comment by walmar** [comment]
Closing a tab via middle mouse button click is also on my list of feature requests that I have not opened yet.
My examples do not include Google Chrome but Mozilla Firefox and Notepad++ for comparison.

In Notepad++ you can even [hide the close button](https://m.youtube.com/watch?v=iI_Ol9OXd-s), but that is less important to me since it is already only displayed for the active tab.

**Comment by dpolivaev** [comment]
Preview 1.12.9_01: now you can use tab pop-up menu to close unselected maps

**Comment by walmar** [comment]
Just for everyone's information:
The implementation does not seem to be exactly what was requested.
It is now possible to close an unselected map.

When comparing the two click approaches, tabs can be closed using the following methods.
* v1.12.8 via two separate left clicks
* v1.12.9_01 alternatively via right click and then nearby left click
