### ISSUE TITLE
"Open mind map from URL"  can't open files from SharePoint Online

### ISSUE THREAD

**Issue by heyvoon** [freeplane/freeplane#235]
When trying to open a .mm file stored in SharePoint Online, Freeplane says file is not found.
![image](https://user-images.githubusercontent.com/3281265/135836486-42365835-d385-410b-8b2b-9df5e3494e25.png)

Found something that might be related 👉 https://github.com/freeplane/freeplane/pull/69

Is this behaviour by default? Can/Should it be fixed?

**Comment by dpolivaev** [comment]
How can I analyze this issue not knowing even a complete URL?

**Comment by heyvoon** [comment]
Well, How can u close the issue even before I answer you?! 
The URL is a SharePoint online URL (Intranet of the company I work for) not a public SharePoint site where I can share it with you.

**Comment by dpolivaev** [comment]
Yes, I do not see any information for problem analysis, therefore the issue is closed.
If you share new information it can be reopened.

**Comment by heyvoon** [comment]
> Yes, I do not see any information for problem analysis, therefore the issue is closed. If you share new information it can be reopened.

Than you should politely ask for the information. I am not a developer nor a programmer. I am just reporting something that is happening. Now, if you don't F care about it is another issue and it's definitely not mine and you can close the case. If you don't want to pay attention to what people are saying, than you shouldn't even be here trying to help.

**Comment by dpolivaev** [comment]
I still read your messages even if the issue is closed.
If you need help feel free to add more information.
If you don't need help it is fine for me.

**Comment by ldmpub** [comment]
Hi,

Sorry to intervene in your dialog, just to share my experience.

Freeplane is a FOSS (free and open source) and high quality software. Dimitry is doing a great job since the beginning of Freeplane and even before (he is a former Freemind developer and he forked the project to build Freeplane .... it was several years ago 👍). He always welcome and guide new developers who what to contribute to correct or improve Freeplane and **he personally pay attention to answer requests of all kinds from end-users in very short delays**. 

Nevertheless Dimitry is not a psychic and as far as I know do not own a crystal ball ... thus you should understand that he can not help you with so few information.

Note: don't worry about giving a full Corporate SharePoint URL because without your credentials (user + password) no one can gain access to your private file nor to any of your server content.
