### ISSUE TITLE
Wrong Spanish translation for "Edge(s)"

### ISSUE THREAD

**Issue by amlopezalonso** [freeplane/freeplane#373]
Hi,

Spanish translation for term "edge(s)" should be not "borde(s)" as it is wrong and lead to confusion with English "border(s)" (of a node) which in Freeplane is also Spanish translated as "borde(s)" (being correct in this case indeed). The reason is that Spanish "borde(s)" means also "edge(s)" in the sense of something's limit which is not the case in Freeplane.

A better Spanish translation for "edge(s)" (though somewhat loose which is fine for a multipurpose graphic tool) should be "camino(s)" which is also closer to English "path(s)". And a more precise term (in graph theory) should be "arista(s)".

Regards,
Antonio

**Comment by euu2021** [comment]
I see that this translation is difficult in all Romance languages. Right now, the translations are like this:

- Spanish: border
- Portuguese (Brazil): border
- Portuguese (Portugal): line
- French: line
- Italian: connection/link

Correct me if I'm wrong, but, from the [Translation-How-To](https://www.freeplane.org/wiki/index.php/Translation_How-To), it seems that the correct procedure here is opening a discussion thread. One thread for all the Romance languages would be nice, because the words are similar.

**Comment by dpolivaev** [comment]
I don't know Spanish. All translations are performed by the community at https://hosted.weblate.org/projects/freeplane/. I think you can fix it there.
