### ISSUE TITLE
Changing the Look and Feel makes the fonts in the preferences window shrink

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#394]
After changing the Look and Feel a couple of times, the fonts start to shrink. Each change in the Look and Feel makes the fonts shrink more, to the point it gets impossible to read:

![image](https://user-images.githubusercontent.com/77707706/169696951-eb076ea0-59c0-4a8d-bdac-7bf302a5972f.png)

Restarting FP makes things go back to normal.

**Comment by rexelbartolome** [comment]
I think that's just the general nature of changing Freeplane settings. Another bug that comes up is that the icon colors don't update when changing LaFs, so if you start out with Flat IntelliJ then pick Flat Darcula, the icon becomes unreadable since it's now a dark icon on a dark background. It's due to the nature of the SVG's being rendered at the start of the program. Therefore, to render an updated set of icons with the proper colors, a restarting Freeplane is required.

I think it's just inevitable for changing big settings in a program, but something that could make it a bit more seamless is to include a "Restart Freeplane" button on the window that shows up after changing settings, then have it be "Ignore" instead of "Okay" 

![image](https://user-images.githubusercontent.com/88552647/169710803-21e80db9-0a7f-4f97-84f9-a1723dd710b0.png)
