### ISSUE TITLE
Option to show connectors behind clouds

### ISSUE THREAD

**Issue by Neeqstock** [freeplane/freeplane#404]
Right now the connectors are showed in front of the clouds. I would like an option to force connectors to be shown behind clouds. Things can get very confused otherwise, especially with floating nodes (see screenshot).

Such option could be inserted in the general Preferences, or as a styling option for single connectors.

![Connectors clutter](https://user-images.githubusercontent.com/15343295/170372981-f1273acd-2258-4e6a-83a3-117d261a5210.png)

**Comment by dpolivaev** [comment]
Preferences…->Defaults->Connectors->Paint connectors behind nodes

**Comment by macmarrum** [comment]
Here's what I can see when I enable the option `Preferences…->Defaults->Connectors->Paint connectors behind nodes` 


![paint_connectors_behind_clouds](https://user-images.githubusercontent.com/7197131/171867830-14846177-cfaf-4587-95e4-2a3df365e893.png)

The fact that the connector is painted over the cloud is actually quite useful. From a visual perspective, I consider a cloud to be part of the background rather than a node.

If this were to change, I would vote to have it as a separate option.

[paint_connectors_behind_clouds.zip](https://github.com/freeplane/freeplane/files/8832784/paint_connectors_behind_clouds.zip)
