### ISSUE TITLE
Change two standards: Selection mode "by click"+ keyboard shortcut [Tab] for Insert new node

### ISSUE THREAD

**Issue by burnuser** [freeplane/freeplane#443]
**Is your feature request related to a problem? Please describe.**

As discussed in #431 in every fresh installation of Freeplane I (have to) change two configurations:

1.) Behaviour - Selection method: "by click" (= Explicit user action gives an expectable explicit result). Actual standard "Delayed" is for newbies and people with handicaps much more confusing and harder to use. And also for experienced users like me, an explicit click is the most comfortable and used solution!
People are trained to expect some standard behaviours from computers. One of this standards is: If You want to select something, ... click on it!
And bringing new people to use Freeplane is much easier when they open Freeplane ... and feel like home! (Compared to other software.)

2.) Keyboard shortcut for "Insert new child node": was [Tab] in Freemind and would also be in Freeplane a much better solution than [Insert]. Because the [TAB] key is very prominent and easy to find and hit.
On the other hand, many keyboards (maybe only German ones, I don't know) have no explicit [Insert] Key at all. Only as alternative function of another key (often in the numeric keypad). Hard to find and bad to use for the maybe most important function in a map!.

**Describe the solution you'd like**
1.) Change out of the box standard for Selection method to "by click"
2.) Change out of the box shortcut for "Insert new child node" to [Tab]

**Describe alternatives you've considered**
Can configure both standards with existing functions.
But must do it separately and - in case of new users, to whom I recommended Freeplane - I must explain this changes. (Not easy on the phone or during a brief encounter.) And without this changes, the user experience is not as good as possible!

**Additional context**
Thinking on newbies, trainees and other users starting with Freeplane. Make the entrance to this new mapping world as easy as possible. Without the need of major behaviour setting changes at 1. start!

**Comment by dpolivaev** [comment]
Changed in Preview 1.10.3_10

**Comment by echo21** [comment]
Hi @dpolivaev,

I highly support support [Loic Joly's request for restoring < ins > as the freeplane default keyboard shortcut for inserting a new child node](https://github.com/freeplane/freeplane/issues/765). I'd like to add another strong argument :

- < ins > key is the de-facto industry standard for inserting new mind map child nodes. Almost all of the commercial and free freeplane alternatives (e.g. MindManagr, MindMeister, XMind, ...) use < ins > instead of < tab > (or at least both of them). To my best knowledge the expensive [MindManager](https://www.mindmanager.com/) by Correl (recently re-branded as [All u do](https://www.alludo.com/)) is the market leader since 1998 (freemind started in 2003 and freeplane forked in 2008). I think that freeplane should not violate de-facto standards by not accepting < ins > key.

User who like < tab > more than < ins > can overwrite the default.
