### ISSUE TITLE
Does freeplane work with IKVM.NET?

### ISSUE THREAD

**Issue by mycall** [freeplane/freeplane#46]
I'd like to interface C# code with freeplane using this library.   Is there any FAQ or tips I should keep in mind before attempting this?   I see possibly creating new WPF or Unity3D interface.

Thx

**Comment by vboerchers** [comment]
I don't believe that ikvm.net would help since this provides code compatibility. This could help to use Freeplane code in an other application. But the most relevant thing is the JVM platform on which Freeplane runs. As with .NET a lot of languages can be used to write code for and to interface with Applications running on the JVM: https://en.wikipedia.org/wiki/List_of_JVM_languages

Volker

**Comment by dpolivaev** [comment]
Please reopen this issue if needed
