### ISSUE TITLE
jump-in: sibling node gets deleted on summary node deletion

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#580]
Based on [test-side.zip](https://github.com/freeplane/freeplane/files/9389122/test-side.zip)

#### Case 1 - delete R
Unexpected:
* `FirstGroupNode` not deleted
* `A right-1` deleted

#### Case 2 - delete S
Unexpected:
* `FirstGroupNode` not deleted
* `B default-1` deleted

**Comment by dpolivaev** [comment]
Are you sure you attached the right mind map? I do not see nodes R and S here

**Comment by macmarrum** [comment]
Yep, wrong attachment. Sorry.

Here's the correct one
[test-side-2.zip](https://github.com/freeplane/freeplane/files/9389657/test-side-2.zip)

**Comment by dpolivaev** [comment]
preview 1.10.4_11

**Comment by dpolivaev** [comment]
Having the first summary node on another side than the actual summary node makes no sense. Therefore I changed a piece of logic responsible for changing sides, copying, moving and deleting of summary nodes.

However, the issue remains tricky because if the left and right nodes both have summary nodes but appear on the same side after jumping out it can still result in inconsistent behavior.

If you discover it please try to think about how to fix it, defining the logic is far from being easy and trivial.

**Comment by dpolivaev** [comment]
And needless to say, your example map can not be fixed, it is illegal. I only made it harder to create such configurations.

**Comment by macmarrum** [comment]
Taking into consideration the difficulty in finding FirstGroupNode belonging to SummaryNode, covered in this issue, and the other issues (below), a thought came to my mind of a possible alternative.
* https://github.com/freeplane/freeplane/issues/583
* https://github.com/freeplane/freeplane/issues/584

If SummaryNode contained nodeID of FirstGroupNode, there would be no need to search for it. Also, there would be no need to disallow operations that would result in grouping nodes of a different side (when creating it or moving nodes in and out).
