### ISSUE TITLE
Width of node not correctly minimized after automatic word wrap

### ISSUE THREAD

**Issue by autoca** [freeplane/freeplane#620]
**Describe the bug**
When a text in a node core wraps automatically, then its width not correctly shrunk down to its possible mininmum.
This is especially annoying if the first word, that gets moved down to the new line, is a longer word. Then there remains a big empty gap at the end of the above first line.
If I manually make a new line with shift+enter, then the width of the node is shrunk ok - no empty gap.

**To Reproduce**
1. Open a new standard map (Min node width: 0; Max node width: 10 cm; Font: SansSerif; Font Size: 10)
2. Add a new node
3. Change the node core to the following text: "longwordlongwordlongwordlongword longwordlongwordlongwordlongword"
4. The 2nd "longwordlongwordlongwordlongword" will be automatically wrapped to a 2nd line but at the end of the 1st line there remains a big empty gap; the width of the node is not minimized as far as possible.

**Expected behavior**
The width of the node should be minimized as far as possible, so that it is not much wider than the word "longwordlongwordlongword" itself.

**Mind map files**
[longwordlongwordlongwordlongword.zip](https://github.com/freeplane/freeplane/files/9477770/longwordlongwordlongwordlongword.zip)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 8.1
 - Java Version 15.0.7

**Comment by autoca** [comment]
Screenshots
Width with automatic word wrap (not good - empty gap):
![grafik](https://user-images.githubusercontent.com/37442404/188163577-b73f59a5-ebc6-4c5c-810c-88bd3bb705d2.png)

Width with manual word wrap (as it should be also for automatic):
![grafik](https://user-images.githubusercontent.com/37442404/188164958-1f096d93-e3a4-43b7-9a16-6bf9bc4baef4.png)

**Comment by dpolivaev** [comment]
It is handled by a library and therefore difficult to fix.

**Comment by walmar** [comment]
I also noticed the automatic wrap before long words without effectively saving node width. I analyzed it and wrote it down to describe it before searching for existing reports.
I have to write that @autoca's report is already well written and I'm sad to read that according to @dpolivaev there is no solution yet.

The issue occurs particularly frequently in German with [compounds](https://en.wikipedia.org/wiki/Compound_(linguistics)) (``Nachfolgend ein Beispiel mit Gedankenkartenknotenzeilenumbruch``):

![Image](https://github.com/user-attachments/assets/b68f5ee9-71f0-4d65-a05d-d770a862bc3d)

Therefore, I think it would be best to prevent further unnecessary investigation for users by either solving the problem, if possible, or by clearly highlighting the annoying behavior as part of a list of known limitations; perhaps [pinned above the issues search bar](https://docs.github.com/en/issues/tracking-your-work-with-issues/administering-issues/pinning-an-issue-to-your-repository). Instead of only labeling it [*wontfix*](https://github.com/freeplane/freeplane/issues?q=state:closed%20label:%22wontfix%22).

**Comment by dpolivaev** [comment]
@walmar I would rather have a known issue page as part of Freeplane online documentation. And any user could contribute it.

Now you can edit https://docs.freeplane.org/user-documentation/known-issues.html and send me your pull request.

**Comment by dpolivaev** [comment]
You can also mention that all such issues can be found at https://github.com/freeplane/freeplane/issues?q=label%3A%22can%27t%20do%22%20OR%20label%3A%22not%20our%20bug%22%20%20OR%20label%3Awontfix

**Comment by walmar** [comment]
@dpolivaev, thank you for creating a dedicated documentation section for the (most impactful) known issues with no foreseeable solution. I will consider a contribution.

Regarding the specific issue topic: This issue generally occurs **when the text reaches a certain length in cm** (<a href="https://freeplanedocumentation.wordpress.com/editing-layout-and-theme/changing-colour-shape-and-text-of-nodes/#shape">#shape - Changing Colour, Shape and Border of Nodes and Edges - Freeplane Documentation</a>)**. The node width is then set to a fixed default value without any individual width adjustment.** This becomes particularly annoying when a longer word reaches the specified text width.

> It is handled by a library and therefore difficult to fix.

https://github.com/freeplane/freeplane/issues/1107#issuecomment-1518691206
> The renderer uses javax.swing.plaf.basic.BasicHTML and HTML renderers, and they are not perfect at required width estimation.

GPT-4.1 nano on **chat**ZZZ**g**ZZ**p**Z**tde**ZZ**utsch .info/en/** answers differently in German and English: [no_indexing.zip](https://github.com/user-attachments/files/20464790/no_indexing.zip) (pw: fp)
