### ISSUE TITLE
Search function does not work on latex nodes

### ISSUE THREAD

**Issue by ecarlevaro** [freeplane/freeplane#732]
### Discussed in https://github.com/freeplane/freeplane/discussions/550

<div type='discussions-op-text'>

<sup>Originally posted by **ecarlevaro** August 10, 2022</sup>
**Expected behaviour:**
The user searches for the term "needle" or variation of it and Freeplane should cycle through the nodes that contain the search term. This was the behaviour in previous versions.

**Current behaviour:**
Freeplane ignores Latex nodes.

See attached video. I tried the latest build on Github on 2 Windows machines with my old and new .mm files.

**How to reproduce**
Create a latex node with "\latex needle" and the term needle will never be found.

[https://1drv.ms/u/s!Ao1u8pZkLvebrIljs7Z6DXe7FdD_ig?e=6HYrRq][(url](https://1drv.ms/u/s!Ao1u8pZkLvebrIljs7Z6DXe7FdD_ig?e=6HYrRq))
</div>

**Comment by germanysverybest** [comment]
Having the same problem in v1.10.6.
Is someone working on this?

**Comment by macmarrum** [comment]
@germanysverybest 

I can see that while both Filter Toolbar and `Edit->Find->Find…` are failing to find the searched term, `Edit->Find->Find and replace…` works for LaTeX content.

Also, Filter Toolbar and `Edit->Find->Find…` fail when searching by "Core, details or note", but they work as expected when searching by "Script Filter", e.g. `node.text.contains('needle')`

So, until the issue is addressed, maybe you could use one of the above workarounds.

**Comment by germanysverybest** [comment]
@macmarrum 
Thanks, that really helps until the issue if fixed.

**Comment by dpolivaev** [comment]
The issue was not labeled as a bug. Now it is, and I am going to address it.
