### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by azzamsa** [freeplane/freeplane#90]
Is this possible to implement dark theme to freeplane ?

Thank you so much for your contribution to community, this app is awesome.

**Comment by matippetts** [comment]
Sure. Absolutely! Very yes, a lot. I couldn't be here without it. Computer Vision Syndrome has whacked my eyesight good and proper, so I need dark-themed everything, if I want to work more than an hour a day. Freeplane supports my needs better than most.

For the look-and-feel (aka shell or skin) of the overall application, a lot depends on the general settings of your desktop. The first thing you'll need to do is set up an appropriate dark theme there -- which is a very OS-specific task. Then from Freeplane's main menu, go into `Tools -> Preferences...`; on the `Appearance` tab, in the first section -- labeled `Look and feel` -- the first control is a combo-list, also labeled `Look and Feel`. Experiment. You could read [these instructions](https://docs.oracle.com/javase/tutorial/uiswing/lookandfeel/index.html) first, if you're into that kind of thing.

Personal experience: I typically run Ubuntu-flavored Linux. Under the Unity desktop, I found `GTK+` to work best. Presumably the same would be true for Gnome 3. More recently I've started using XFCE, which I find works best with the `Default` setting. If nothing in the drop-down list does as you want, there's a tool-tip with a hint about how to roll a custom solution. (You'll need to configure the classpath and wave a chicken at it. Also, definitely read [those instructions](https://docs.oracle.com/javase/tutorial/uiswing/lookandfeel/index.html) I mentioned. Good luck.)

Now, for the actual content of the map: You'll want to edit the map style (`F11` by default). Once you have something you like, save it as a template. A template is just a normal Mindmap that happens to be in the `templates` sub-directory of your home folder. So, where's your home folder? Trick question. But the easiest way to find out is to go the main menu and click on `Tools -> Open user directory`. Wherever you find yourself, there you are. 

Once you have a template saved in the `templates` directory, you can set it as the default for all new files. Starting at the main menu, go to `Tools -> Preferences...` On the `Environment` tab, scroll down to the `Files` section and change the value in the `Standard template file` combo box.

This
[style_dark-basic.mm.zip](https://github.com/freeplane/freeplane/files/1591598/style_dark-basic.mm.zip)
 is mine. It's overly complex, and a sad testament to the lack of CSS support in Freeplane. It may be a little broken, because of missing icons or conditional styles. And it thinks Morrissey is still relevant. But it's definitely dark.

**Comment by azzamsa** [comment]
Sure, thank you so much. 

> For the look-and-feel (aka shell or skin) of the overall application

Yes, I use dark-theme all the time, and change freeplane theme to GTK+ works for me.

> Personal experience: I typically run Ubuntu-flavored Linux. Under the Unity desktop, I found GTK+ to 

I use Debian 9 with i3wm, do you have a way to make java based app font not glitched ?

> Now, for the actual content of the map: You'll want to edit the map style (F11 by default). Once you have 
> Once you have a template saved in the templates directory, you can set it as the default for all new 
files.

Thanks lot for very complete explanation and thank you for the template file :)

Thank you so much, you describe each step very very clear, again thank you so much.

**Comment by fnatter** [comment]
hello azzamsa,

> I use Debian 9 with i3wm, do you have a way to make java based app font not glitched ?

Not sure if I get the right context. If you are having font rendering problems in freeplane,
try these suggestions:
http://www.freeplane.org/wiki/index.php/Rendering_Issues

Cheers and Best Regards,
Felix

**Comment by azzamsa** [comment]
@fnatter thanks lot.  

I have used ` -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true ` in my bash long time ago, but I have to run freeplane from terminal in order to pick that setting.

now I commented out that line and just use 
``` bash
 export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
```
in certain terminal session, then run freplane in that session. Using this export does not solved the glitch 100% but slightly better than before.

Changing freeplane antialias setting does not works for me.

**Comment by BaptisteDebes** [comment]
Hi, 

I'm a windows user, and not an expert. I've used the dark template you provided (it's great) but I don't know how to set the theme using what you said, which seems to concern linux users ? I'm using a windows dark theme (by default on a surface 4). 

Thanks in advance !

**Comment by azzamsa** [comment]
@matippetts works well. thank you so much :)

**Comment by dpolivaev** [comment]
Dark theme support added in Freeplane 1.7.10 preview 02

**Comment by AtomicNess123** [comment]
i'm on a mac. How could I use a dark theme? I understand I must set it up first. Could somebody explain me how? Thanks! "You'll want to edit the map style (F11 by default)." But here I can change many colors but none associated to the background.

**Comment by sorenwacker** [comment]
Where can I find that option? I would expect it under View.

![image](https://user-images.githubusercontent.com/3391614/202247963-30d23995-db02-48e3-9fd9-c5614f196d86.png)

**Comment by dpolivaev** [comment]
Preferences…->Appearance->Look and feel->Look and Feel

**Comment by hohwille** [comment]
Great that you added a Dark Theme. However, it does not change the colors of the minmap itself but just the menu and icons around. I could manually change the background color of every mindmap to black but then I have black text on black background. Changing the font color of the node-texts to white did not have any effect.
IMHO still not there. Am I missing something?

**Comment by hohwille** [comment]
Ah, so I have to recreate my mindmaps also with darkmode template and then copy all over.
Can someone with dark-mode and someone else with white mode share mindmaps then and collaborate?
I would rather suggest/expect the dark mode to invert the mindmap style colors.

**Comment by macmarrum** [comment]
Mind map colors (theme) and Freeplane look-and-feel colors (theme) are two different beasts. You can have a light UI but dark mind maps. And vice versa.

I think there's no ready solution to convert a light mind-map template to dark colors.

You can choose a dark-colors template from the ones delivered with Freeplane.

First change your associate template
`Format->Manage Styles->Manage followed and associated mind maps` → **Associated template**: `Change` → **File types**: `Standard templates (*.mm)` → Select your new `dark_...` template

Then use `Copy styles` or `Replace styles`. 
`Edit->Undo` if needed.

If you don't like those, you might need to manually change your light mind map to dark colors.
