### ISSUE TITLE
nodes position changes with zoom level

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#902]
Changing the zoom level changes the node position:
![javaw_6fuTQBGFfm](https://user-images.githubusercontent.com/77707706/208685485-ff6a1b7f-b2cb-46ed-862c-d438bac8d1ec.gif)

**Comment by dpolivaev** [comment]
Me: Write a short poem saying "Please be so kind as to always attach the mind map file because it saves me time"
AI: Please be so kind as to always
attach the mind map file,
it saves me time, you see.
No need to search or roam,
just click and it's all there,
a helpful tool, a guiding light,
to lead me through the day and night.
So please, dear friend, remember this,
attach that file, it's worth the bliss.

**Comment by euu2021** [comment]
[EXAMPLE zoom.zip](https://github.com/freeplane/freeplane/files/10298831/EXAMPLE.zoom.zip)

**Comment by dpolivaev** [comment]
Preview 1.11.1_06
